  name: 提 Bug
  description: Bug Report、反馈问题、提 Bug
  labels: bug
  body:
    - type: textarea
      id: description
      attributes:
        label: 问题描述
        description: |
          简明扼要的描述你的问题
          如果可以的话，附上截图
      validations:
        required: true
    - type: textarea
      id: reproduce
      attributes:
        label: 如何复现
        description: |
          1. 
          2. 
          3. 
          4. 
    - type: textarea
      id: code
      attributes: 
        label: 代码
        render: Typescript
    - type: textarea
      id: expected-behavior
      attributes:
        label: 预期结果
        description: 简明扼要的说明你期待的结果
      validations:
        required: true
    - type: textarea
      id: version
      attributes:
        label: 环境描述/版本信息
        description: |
          - OS: [e.g. iOS]
          - Browser [e.g. chrome, safari]
          - Version [e.g. 22]
          - Node
          - fes -V
          - package.json
      validations:
        required: true
    - type: textarea
      id: addition
      attributes:
        label: 其它补充内容
        placeholder: 任何和这个问题有关的额外内容
