<template>
    <FSpace>
        <FAlert
            showIcon
            closable
            type="info"
            message="常规信息提示内容"
            description="辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助"
        />
        <FAlert
            showIcon
            closable
            type="success"
            message="正确表达提示内容"
            description="辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助"
        />
        <FAlert
            showIcon
            closable
            type="warning"
            message="警示表达提示内容"
            description="辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助"
        />
        <FAlert
            showIcon
            closable
            type="error"
            message="错误表达提示内容"
            description="辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助信息提示内容辅助"
        />
    </FSpace>
</template>
